env:
    CIRRUS_CLONE_DEPTH: 1

container:
  image: ubuntu:14.04
  cpu: 0.5
  memory: 512M

cache_task:
  name: 1
  name_cache:
    folder: myfolder
  script:
    - ls
    - mkdir -p myfolder
    - ls
    - echo pro >> hi.txt
    - echo inside myfolder >> myfolder/myfolder.txt
    - ls -R
    - apt install -y -qq curl
    - curl -s -X POST --data-binary @myfolder.tar.gz http://$CIRRUS_HTTP_CACHE_HOST/name-mykey
