pipe:
  name: Build Site and Validate Links
  steps:
    - image: ubuntu:20.04
      build_script: cat /etc/os*
    - image: alpine:edge
      validate_script: cat /etc/os*

task:
    name: source t
    container:
        image: ubuntu:20.04
    t_script: source t
