env:
    CIRRUS_CLONE_DEPTH: 1

container:
  image: ubuntu:14.04
  cpu: 0.5
  memory: 512M

test_task:
  name: cache
  myfolder_cache:
    folder: myfolder
  script:
    - mkdir -p myfolder
    - cat myfolder/hi.txt
    - echo pro >> myfolder/hi2.txt
    - cat myfolder/hi2.txt
    - apt install -y -q curl
    - curl -s -X POST --data-binary @myfolder.tar.gz http://$CIRRUS_HTTP_CACHE_HOST/myfolder-mykey 
