env:
    CIRRUS_CLONE_DEPTH: 1

container:
  image: ubuntu:14.04
  cpu: 0.5
  memory: 512M

env_task:
  name: env task
  script: env

test_task:
  hi_cache:
    folder: test
  populate_script:
    - mkdir -p test
    - echo pro > test/ok
  test_script:
    - cat test/ok
    - apt install curl -y
    - curl -s -X POST --data-binary @test/ok http://$CIRRUS_HTTP_CACHE_HOST/name-mykey
