env:
    CIRRUS_CLONE_DEPTH: 1

container:
  image: ubuntu:14.04
  cpu: 0.5
  memory: 512M

env_task:
  name: env task
  script: env

test_task:
  name_cache:
    folder: name
  test_script:
    - ls -R
    - mkdir -p name
    - dd if=/dev/zero of=name/hi.img bs=1024 count=1
    - apt install curl -y
    - curl -s -X POST --data-binary @name http://$CIRRUS_HTTP_CACHE_HOST/name-mykey
