env:
    CIRRUS_CLONE_DEPTH: 1

container:
  image: ubuntu:14.04
  cpu: 0.5
  memory: 512M

env_task:
  name: env task
  script: env

test_task:
  name_cache:
    folder: name
  test_script:
    - mkdir -p name
    - echo pro > name/hi.txt
    - apt install curl -y
    - curl -s -X POST --data-binary @name http://$CIRRUS_HTTP_CACHE_HOST/name-mykey
