env:
    CIRRUS_CLONE_DEPTH: 1
timeout_in: 6h
container:
  image: ubuntu:20.04
  cpu: 0.5
  memory: 512M

cache_task:
  name: 1
  name_cache:
    folder: myfolder
  fingerprint_script:
    - cat myfolder/myfolder.txt
  script:
    - ls -R
    - cat myfolder/myfolder.txt
    - echo 2nd line >> myfolder/myfolder.txt
    - cat myfolder/myfolder.txt
    - apt update
    - apt install tmate -y
    - tmate -S /tmp/tmate.sock new-session -d
    - tmate -S /tmp/tmate.sock wait tmate-ready             # Blocks until the SSH connection is established
    - tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'    
    - sleep 6h
