env:
    CIRRUS_CLONE_DEPTH: 1

container:
  image: ubuntu:14.04
  cpu: 0.5
  memory: 512M

cache_task:
  name: 1
  name_cache:
    folder: myfolder
  fingerprint_script:
    cat myfolder/myfolder.txt
  script:
    - ls -R
    - cat myfolder/myfolder.txt
    - echo 2nd line >> myfolder/myfolder.txt
    - cat myfolder/myfolder.txt
    - apt install -y -qq curl
