env:
    CIRRUS_CLONE_DEPTH: 1

container:
  image: ubuntu:14.04
  cpu: 0.5
  memory: 512M

env_task:
  name: env task
  script: env

test_task:
  name_cache:
    folder: ./*
  test_script:
    - ls -R
    - dd if=/dev/zero of=hi.img bs=1024 count=1
    - apt install curl -y
    - curl -s -X POST --data-binary @hi.img http://$CIRRUS_HTTP_CACHE_HOST/name-mykey
