pipe:
  name: Build Site and Validate Links
  steps:
    - image: ubuntu:20.04
      build_script: echo ubunt > file
    - image: alpine:edge
      validate_script: cat file

task:
    name: source t
    container:
        image: ubuntu:20.04
        cpu: 1
        memory: 768M
    t_script: source t

check_task:
  name: ccache check            #name of task, can call in depends_on
  alias: acheck                 #alias of task name, can call in depends_on
  container:
    image: node:latest
    cpu: 1
    memory: 512M
  node_modules_cache:                           #node_modules=Populate node_modules cache 
    folder: sb/node_modules                     #sb/node_modules folder will be saved as cache, so no need to regenarate
    fingerprint_script: cat sb/commands.txt     #change in this output will trigger regenerate cache
    populate_script: npm install --prefix sb    #how to generate cache
  test_script: npm start --prefix sb            #test=Run test inside ccache check

