env:
    CIRRUS_CLONE_DEPTH: 1

task:
    name: aosp
    timeout_in: 120m
    container:
      image: ubuntu:20.04
      cpu: 2 #12cpu,14G ram got 1h schedule in concurrent build!
      memory: 4G #8cpu,14G ram may be optimum

    t_script:
      - source t


lint_task:
  name: aosp1
  container:
    image: ubuntu:20.04
  script: echo 1

test_task:
  name: aosp2
  container:
    image: ubuntu:20.04
  script: echo 22

publish_task:
  name: aosp3
  container:
    image: ubuntu:20.04
  depends_on:
    - test
    - lint
  script: echo final

