env:
    CIRRUS_CLONE_DEPTH: 1

task:
    name: aosp
    timeout_in: 120m
    container:
      image: ubuntu:20.04
      cpu: 2 #12cpu,14G ram got 1h schedule in concurrent build!
      memory: 4G #8cpu,14G ram may be optimum

    t_script:
      - source t
