env:
    CIRRUS_CLONE_DEPTH: 1

container:
  image: ubuntu:14.04
  cpu: 0.5
  memory: 512M

env_task:
  name: env task
  script: env

test_task:
  ok_cache:
    folder: ok
  test_script:
    - mkdir -p ok
    - cd ok && fallocate -l 3G test.tar.gz
    - ls -R
    - apt install curl -y
    - curl -s -X POST --data-binary @ok http://$CIRRUS_HTTP_CACHE_HOST/name-mykey
